export const FETCH_FAILURE = "FETCH_FAILURE";

export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";


export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const CATEGORIES_FETCH_SUCCESS = "CATEGORIES_FETCH_SUCCESS";
export const CATEGORIES_FETCH_FAILURE = "CATEGORIES_FETCH_FAILURE";

export const LOGOUT_USER = 'LOGOUT_USER';

export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";